# Generated by Django 4.0 on 2021-12-17 02:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
